core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import crear_proyecto, lista_empleados, lista_proyectos, mover_tabla, registro_cliente, registro_empleado, mover_ticket, update_table_color
from django.contrib.auth.views import LoginView, LogoutView
from . import views



urlpatterns = [
    #***************************************La página de inicio será el TRELLO**************************************************
    path('', views.index, name='index'), 
    
#****************************** LOGIN ******************************#
    path('iniciar-sesion/', LoginView.as_view(template_name='core/login.html'), name='login'), #http://127.0.0.1:8000/iniciar-sesion/
    path('cerrar-sesion/', LogoutView.as_view(next_page='login'), name='logout'), #Log out que lleva al inicio de sesión

#****************************** EMPLEADOS ******************************#
    path('empleados/', lista_empleados, name='lista_empleados'), #http://127.0.0.1:8000/empleados/
    path('eliminar_empleado/<int:empleado_id>/', views.eliminar_empleado, name='eliminar_empleado'), #para eliminar empleado
    path('perfil/<int:empleado_id>/', views.perfil_empleado, name='perfil_empleado'), #http://127.0.0.1:8000/perfil
    path('descargar-pdf/<int:empleado_id>/', views.descargar_pdf, name='descargar_pdf'), #para descargar pdf del empleado seleccionado
    path('editar_empleado/<int:empleado_id>/', views.editar_empleado, name='editar_empleado'), #http://127.0.0.1:8000/editar (por id de empleado)
    path('registrarme/', registro_empleado, name='registro_empleado'), #http://127.0.0.1:8000/registrarme/

#****************************** CLIENTE ******************************#
 
    path('clientes/', views.lista_clientes, name='lista_clientes'), #http://127.0.0.1:8000/lista_clientes
    path('registrar-cliente/', registro_cliente, name='registro_cliente'), #http://127.0.0.1:8000/registrar-cliente/
    path('editar_cliente/<int:cliente_id>/', views.editar_cliente, name='editar_cliente'), #http://127.0.0.1:8000/editar (por id de cliente)
    path('eliminar_cliente/<int:cliente_id>/', views.eliminar_cliente, name='eliminar_cliente'), #para eliminar cliente
    path('perfil_cliente/<int:cliente_id>/', views.perfil_cliente, name='perfil_cliente'),#Perfil clientes
    path('archivo/<int:archivo_id>/eliminar/', views.eliminar_archivo, name='eliminar_archivo'), #eliminar archivo
    path('guardar_archivos/', views.guardar_archivos, name='guardar_archivos'),#Guardar archivos clientes
    path('cambiar_nombre_archivo/<int:archivo_id>/', views.cambiar_nombre_archivo, name='cambiar_nombre_archivo'), #edición nombre archivo
    path('descargar_archivo/<int:archivo_id>/', views.descargar_archivos, name='descargar_archivos'),
   
#****************************** TRELLO ******************************#
    path('eliminar_tabla/<int:table_id>/', views.eliminar_tabla, name='eliminar_tabla'),#Eliminar tabla
    path('crear-tabla/', views.crear_tabla, name='crear_tabla'),#Crear tabla
    path('table/<int:table_id>/', views.table_detail, name='table_detail'),#Id de la tabla en especifico
    path('table/<int:table_id>/ticket/create/', views.ticket_create, name='ticket_create'),#Crear tickets
    path('ticket/<int:ticket_id>/update/', views.ticket_update, name='ticket_update'),#actualizar tickets
    path('ticket/<int:ticket_id>/delete/', views.ticket_delete, name='ticket_delete'),#eliminar tickets
    path('mover_tabla/<int:table_id>/', mover_tabla, name='mover_tabla'),

#****************************** PROYECTOS Y TAREAS ******************************#
    path('proyectos/crear/', views.crear_proyecto, name='crear_proyecto'),
    path('proyectos/', lista_proyectos, name='lista_proyectos'),
    path('proyectos/<int:proyecto_id>/eliminar', views.eliminar_proyecto, name='eliminar_proyecto'),
    path('proyectos/<int:proyecto_id>/editar/', views.editar_proyecto, name='editar_proyecto'),

    path('tareas/crear/', views.crear_tarea, name='crear_tarea'),
    path('tareas/', views.lista_tareas, name='lista_tareas'),
    path('tareas/<int:tarea_id>/editar', views.editar_tarea, name='editar_tarea'),
    path('tareas/<int:tarea_id>/eliminar', views.eliminar_tarea, name='eliminar_tarea'),
    path('mover_ticket/<int:ticket_id>/a_tabla/<int:table_id>/', mover_ticket, name='mover_ticket'),
    path('update_table_color/<int:table_id>/', update_table_color, name='update_table_color'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mi_proyecto/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from core.views import index
from mi_proyecto.settings import STATIC_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),  # Incluye las URLs de la app core
    
]

handler404 = 'core.views.handler404'

core/models.py
# Create your models here.
from typing import Iterable
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


#****************************** EMPLEADO ******************************#

#****************************** MODELO EMPLEADO ******************************#
from django.contrib.auth.models import AbstractUser
from django.db import models

class Empleado(AbstractUser):
    ROL_CHOICES = [
        ('admin', 'Administrador'),
        ('empleado', 'Empleado'),
        ('ventas', 'Ventas'),
        ('marketing', 'Marketing'),
        ('redes_sociales', 'Redes Sociales'),
        ('desarrollo', 'Desarrollo')
    ]

    rol = models.CharField(max_length=120, choices=ROL_CHOICES, default='admin', null=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    telefono = models.IntegerField(null=True, blank=True)
    direccion = models.CharField(max_length=120, null=True, blank=True)
    num_seguridad_social = models.IntegerField(null=True, blank=True)
    telefono2 = models.IntegerField(null=True, blank=True)
    foto = models.ImageField(upload_to='images/', null=True, blank=True)
    foto_dni = models.ImageField(upload_to='dnis/', null=True, blank=True)
    foto_dni2 = models.ImageField(upload_to='dnis/', null=True, blank=True)
    fecha_alta = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


#****************************** CLIENTE ******************************#

#****************************** MODELO CLIENTE ******************************#
class Cliente(models.Model):
    # Opciones de tipo de cliente
    TIPO_CHOICES = [
        ('empresa', 'Empresa'),
        ('particular', 'Particular'),
        ('proveedor', 'Proveedor'),
        ('leads', 'Leads')
    ]

    nombre = models.CharField(max_length=120)
    nombre_comercial = models.CharField(max_length=120, null=True, blank=True)
    nif = models.CharField(max_length=9, null=True, blank=True)
    tipo = models.CharField(max_length=120, choices=TIPO_CHOICES, default='empresa', null=True, blank=True)
    razon_social = models.CharField(max_length=120, null=True, blank=True)
    telefono = models.IntegerField(null=True, blank=True)
    telefono2 = models.IntegerField(null=True, blank=True)
    direccion = models.CharField(max_length=120, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    notas = models.TextField(null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)
    web = models.URLField(null=True, blank=True)

    def __str__(self):
        nombre = self.nombre or ''
        nif = self.nif or ''
        return f"{nombre} {nif}".strip()

        



#****************************** PROYECTO ******************************#

#****************************** MODELO PROYECTO ******************************#
class Proyecto(models.Model):
    PRIORIDAD_CHOICES = [
        ('alta', 'Alta'),
        ('muy_alta', 'Muy Alta'),
        ('media', 'Media'),
        ('baja', 'Baja'),
        ('muy_baja', 'Muy Baja'),
        ('sin_prioridad', 'Sin Prioridad')
    ]
    ESTADOS_CHOICES = [
        ('pendiente', 'Pendiente'),
        ('activo', 'Activo'),
        ('finalizado', 'Finalizado'),
        ('cancelado', 'Cancelado'),
        ('permanente', 'Permanente')
    ]
    TIPO_CHOICES = [
        ('1ª Justificacion', '1ª Justificacion'),
        ('2ª Justificacion', '2ª Justificacion'),
        ('Acuerdos', 'Acuerdos'),
        ('Diseño Gráfico', 'Diseño Gráfico'),
        ('E-Commerce', 'E-Commerce'),
        ('Factura electrónica', 'Factura electrónica'),
        ('Gestión Clientes', 'Gestión Clientes'),
        ('Gestión Procesos', 'Gestión Procesos'),
        ('Kit Digital', 'Kit Digital'),
        ('Marketing', 'Marketing'),
        ('Solicitud KD', 'Solicitud KD'),
        ('Redes Sociales', 'Redes Sociales'),
        ('SEO', 'SEO'),
        ('Web', 'Web'), 
        ('TPV', 'TPV'), 
        ('Diseño Gráfico', 'Diseño Gráfico'),
        ('URL', 'URL')
    ]
    nombre = models.CharField(max_length=120)
    descripcion = models.TextField(null=True, blank=True)
    fecha_inicio = models.DateField(null=True, blank=True)
    fecha_fin = models.DateField(null=True, blank=True)
    num_acuerdo = models.IntegerField(null=True, blank=True)
    prioridad = models.CharField(max_length=120, choices=PRIORIDAD_CHOICES, default='sin_prioridad', null=True, blank=True)
    estado = models.CharField(max_length=120, choices=ESTADOS_CHOICES, default='pendiente', null=True, blank=True)
    valor = models.IntegerField(null=True, blank=True)
    tipo = models.CharField(max_length=120, choices=TIPO_CHOICES, null=True, blank=True)
    firma_acuerdo = models.DateField(null=True, blank=True)
    fecha_facturacion = models.DateField(null=True, blank=True)
    num_factura = models.IntegerField(null=True, blank=True)
    fecha_cobro_IVA = models.DateField(null=True, blank=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    empleados = models.ManyToManyField(Empleado)

    def __str__(self):
        return self.nombre 

#****************************** TAREAS ******************************#

#****************************** MODELO TAREAS ******************************#
class Tareas(models.Model):
    PRIORIDAD_CHOICES = [
        ('alta', 'Alta'),
        ('muy_alta', 'Muy Alta'),
        ('media', 'Media'),
        ('baja', 'Baja'),
        ('muy_baja', 'Muy Baja'),
        ('sin_prioridad', 'Sin Prioridad')
    ]
    ESTADOS_CHOICES = [
        ('pendiente', 'Pendiente'),
        ('activo', 'Activo'),
        ('finalizado', 'Finalizado'),
        ('cancelado', 'Cancelado'),
        ('permanente', 'Permanente')
    ]
    nombre = models.CharField(max_length=120)
    descripcion = models.TextField(null=True, blank=True)
    fecha_inicio = models.DateField(null=True, blank=True)
    fecha_fin = models.DateField(null=True, blank=True)
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, null=True, blank=True)
    prioridad = models.CharField(max_length=120, choices=PRIORIDAD_CHOICES, default='sin_prioridad', null=True, blank=True)
    estado = models.CharField(max_length=120, choices=ESTADOS_CHOICES, default='pendiente', null=True, blank=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, default=1)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.nombre
    
#****************************** NOTAS ******************************#
class Notas(models.Model):
    titulo = models.CharField(max_length=120)
    descripcion = models.TextField(null=True, blank=True)
    fecha_creación = models.DateField(auto_now_add=True, null=True, blank=True, editable=False)
    fecha_editado = models.DateField(auto_now=True, null=True, blank=True, editable=False)

    def __str__(self):
        return self.titulo
    
#****************************** TRELLO ******************************#
        
#****************************** MODELO TABLA ******************************#
class Table(models.Model):
    name = models.CharField(max_length=100)
    header_color = models.CharField(max_length=7, default='#ffffff')
    def __str__(self):
        return self.name

#****************************** MODELO TICKETS ******************************#
class Ticket(models.Model):
    table = models.ForeignKey(Table, related_name='tickets', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)  # Campo auto-completado
    
    def __str__(self):
        return self.title


#****************************** MODELO ARCHIVOS_TICKETS ******************************#
class TicketAttachment(models.Model):
    ticket = models.ForeignKey(Ticket, related_name='attachments', on_delete=models.CASCADE)
    file = models.FileField(upload_to='ticket_attachments/')
    
#****************************** MODELO ARCHIVO ******************************#
#Clase archivo para poder subir cualquier numero de archivos al cliente
class Archivo(models.Model):
    cliente = models.ForeignKey(Cliente, related_name='archivos', on_delete=models.CASCADE, null=True, blank=True)
    archivo = models.FileField(upload_to='archivos_clientes/')
    name = models.CharField(max_length=255, null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)
    Proyecto = models.ForeignKey(Proyecto, related_name='archivos', on_delete=models.CASCADE, null=True, blank=True)
    Tareas = models.ForeignKey(Tareas, related_name='archivos', on_delete=models.CASCADE, null=True, blank=True)
    tickets = models.ForeignKey(Ticket, related_name='archivos', on_delete=models.CASCADE, null=True, blank=True)

    def save(self, *args, **kwargs):
        # Si el objeto es nuevo (no tiene ID), asigna la descripción y el nombre
        if not self.pk:  # Esto verifica si el objeto ya existe
            self.descripcion = str(self.archivo)  # Solo se asigna al crear
        self.name = str(self.archivo)  # Asigna el nombre del archivo cuando quiera, ya que se puede editar
        super().save(*args, **kwargs)  # Llama a la función save original


#****************************** MODELO ETIQUETAS ******************************#
class Tag (models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=7, default='#007bff')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

core/templates/core/crear_tabla.html
<h1>Crear Nueva Tabla</h1>
<title>{% block title %}Tabla-Navegatel{% endblock %}</title>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Crear Tabla</button>
</form>

core/templates/core/crear_tarea.html
<!-- templates/core/crear_tarea.html -->

{% extends 'base.html' %}
<title>{% block title %}Tarea-Navegatel{% endblock %}</title>
{% block content %}
<div class="container">
    <h2>Crear Tarea</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_nombre">Nombre:</label>
            <input type="text" class="form-control" id="id_nombre" name="nombre">
        </div>
        <div class="form-group">
            <label for="id_descripcion">Descripción:</label>
            <textarea class="form-control" id="id_descripcion" name="descripcion"></textarea>
        </div>
        <div class="form-group">
            <label for="id_fecha_inicio">Fecha de Inicio:</label>
            <input type="date" class="form-control" id="id_fecha_inicio" name="fecha_inicio">
        </div>
        <div class="form-group">
            <label for="id_fecha_fin">Fecha de Fin:</label>
            <input type="date" class="form-control" id="id_fecha_fin" name="fecha_fin">
        </div>
        <div class="form-group">
            <label for="id_proyecto">Proyecto:</label>
            <select class="form-control" id="id_proyecto" name="proyecto">
                {% for proyecto in proyectos %}
                    <option value="{{ proyecto.id }}">{{ proyecto.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            
            <label for="id_prioridad">Prioridad:</label>
            <select class="form-control" id="id_prioridad" name="prioridad">
                {% for value, label in PRIORIDAD_CHOICES %}
                    <option value="{{ value }}">{{ label }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="id_estado">Estado:</label>
            <select class="form-control" id="id_estado" name="estado">
                {% for value, label in ESTADOS_CHOICES %}
                    <option value="{{ value }}">{{ label }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="id_cliente">Cliente:</label>
            <select class="form-control" id="id_cliente" name="cliente">
                {% for cliente in clientes %}
                    <option value="{{ cliente.id }}">{{ cliente.nombre }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="id_empleado">Empleado:</label>
            <select class="form-control" id="id_empleado" name="empleado">
                {% for empleado in empleados %}
                    <option value="{{ empleado.id }}">{{ empleado.first_name }} {{ empleado.last_name }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock %}

core/templates/core/editar_empleado.html
{% extends 'base.html' %}
<title>{% block title %}Empleado-Navegatel{% endblock %}</title>
{% load static %}

{% block navegar %}
<li class="nav-item">
    <form action="{% url 'logout' %}" method="post" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-link nav-link" style="border: none; padding: 0; background: none;">Cerrar sesión</button>
    </form>
</li>
{% endblock %}

{% block content %}
<style>
    .login-container {
        background-color: #ffffff;
        border-radius: 8px;
        padding: 40px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        max-width: 600px;
        width: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        margin: 0 auto;
    }
    
    .logo {
        text-align: center;
        margin-bottom: 20px;
    }
    
    .logo img {
        max-width: 180px;
    }
    
    .form-group {
        margin-bottom: 20px;
        width: 100%;
    }
    
    .form-group label {
        display: block;
        color: #333;
        margin-bottom: 8px;
    }
    
    .form-group input,
    .form-group select {
        width: calc(100% - 24px);
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 6px;
        font-size: 16px;
    }
    
    .form-group input:focus,
    .form-group select:focus {
        border-color: #007bff;
        outline: none;
    }
    
    .login-button {
        margin: 12px;
        width: calc(100% - 24px);
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 12px;
        border-radius: 6px;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s;
    }
    
    .login-button:hover {
        background-color: #0767ce;
    }
    
    .cancel-button {
        margin: 12px;
        width: calc(100% - 24px);
        background-color: #ccc;
        color: #fff;
        border: none;
        padding: 12px;
        border-radius: 6px;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.3s;
    }
    
    .cancel-button:hover {
        background-color: #999;
    }
</style>

<div class="login-container">
    <div class="logo">
        <img src="https://navegatel.org/wp-content/uploads/2022/08/logo-navegatel-grande.webp" alt="Logo">
    </div>
   
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            {{ form.first_name.label_tag }}
            {{ form.first_name }}
        </div>
        
        <div class="form-group">
            {{ form.last_name.label_tag }}
            {{ form.last_name }}
        </div>
        
        <div class="form-group">
            {{ form.email.label_tag }}
            {{ form.email }}
        </div>
        
        <div class="form-group">
            {{ form.rol.label_tag }}
            {{ form.rol }}
        </div>
        
        <div class="form-group">
            {{ form.telefono.label_tag }}
            {{ form.telefono }}
        </div>
        
        <div class="form-group">
            {{ form.telefono2.label_tag }}
            {{ form.telefono2 }}
        </div>
        
        <div class="form-group">
            {{ form.fecha_nacimiento.label_tag }}
            {{ form.fecha_nacimiento }}
        </div>
        
        <div class="form-group">
            {{ form.direccion.label_tag }}
            {{ form.direccion }}
        </div>
        
        <div class="form-group">
            {{ form.num_seguridad_social.label_tag }}
            {{ form.num_seguridad_social }}
        </div>
        
        <div class="form-group">
            {{ form.foto_dni.label_tag }}
            {{ form.foto_dni }}
        </div>
        
        <div class="form-group">
            {{ form.foto_dni2.label_tag }}
            {{ form.foto_dni2 }}
        </div>
        
        <div class="form-group">
            {{ form.fecha_alta.label_tag }}
            {{ form.fecha_alta }}
        </div>
        
          
    
        <button type="submit" class="login-button">Confirmar cambios</button>
        <a href="{% url 'lista_empleados' %}" class="cancel-button">Cancelar</a>
    </form>
</div>
{% endblock %}

core/templates/core/error.html
<!DOCTYPE html>
<title>{% block title %}Error-Navegatel{% endblock %}</title>
<html>
<head>
    <title>Página no encontrada</title>
</head>
<body>
    <h1>Lo sentimos, la página que buscas no existe.</h1>
    <p>Puedes regresar a la <a href="{% url 'table_list' %}">página principal</a>.</p>
</body>
</html>

core/templates/core/login.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Login-Navegatel{% endblock %}</title>
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css\login.css' %}">

<div class="container mt-4 login-container">
    <div class="logo">
        <img src="https://navegatel.org/wp-content/uploads/2022/08/logo-navegatel-grande.webp" alt="Logo">
    
    </div>
   
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Usuario</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="id_password">Contraseña</label>
            {{ form.password }}
        </div>
        <button type="submit" class="btn btn-primary login-button">Iniciar Sesión</button>
    </form>
    <p class="create-account">¿No tienes una cuenta? <a href="{% url 'registro_empleado' %}">Regístrate aquí</a></p>
</div>
{% endblock %}

core/templates/core/ticket_form.html
<!DOCTYPE html>
<html lang="es">
<head>
    <title>{% block title %}ticket-Navegatel{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear/Actualizar Ticket</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    {% load static %}
<link rel="stylesheet" href="{% static 'css\ticket_form.css' %}">
   
</head>
<body>
    <div class="container">
        <a href="#" onclick="history.go(-1)" style="position: absolute; top: 10px; left: 10px; color: #333; text-decoration: none;"><i class="fas fa-arrow-left"></i> Volver</a>
        <h1>Crear/Actualizar Ticket</h1>
        <form id="ticket-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Título:</label>
                <input type="text" name="title" id="id_title" class="form-control" placeholder="Título del ticket" value="{{ ticket_form.instance.title }}">
            </div>
            <div class="form-group">
                <label for="id_description">Descripción:</label>
                <textarea name="description" id="id_description" class="form-control" rows="4" placeholder="Descripción del ticket">{{ ticket_form.instance.description }}</textarea>
            </div>
            <div class="form-group">
                <label for="id_file">Archivos adjuntos:</label>
                <div class="drop-area" id="drop-area">
                    Arrastra y suelta tus archivos aquí o haz clic para seleccionar
                    <input type="file" name="file" id="id_file" class="form-control" multiple style="display: none;">
                </div>
                <div class="preview-container" id="preview-container">
                    <!-- Mostrar imágenes ya cargadas -->
                    {% for attachment in attachments %}
                        <img src="{{ attachment.file.url }}" alt="Archivo adjunto" class="preview-image existing-image">
                    {% endfor %}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const dropArea = document.getElementById('drop-area');
            const fileInput = document.getElementById('id_file');
            const previewContainer = document.getElementById('preview-container');
            const form = document.getElementById('ticket-form');

            let allFiles = [];

            dropArea.addEventListener('click', () => fileInput.click());

            dropArea.addEventListener('dragover', (event) => {
                event.preventDefault();
                dropArea.classList.add('hover');
            });

            dropArea.addEventListener('dragleave', () => dropArea.classList.remove('hover'));

            dropArea.addEventListener('drop', (event) => {
                event.preventDefault();
                dropArea.classList.remove('hover');
                const files = event.dataTransfer.files;
                handleFiles(files);
            });

            fileInput.addEventListener('change', () => {
                const files = fileInput.files;
                handleFiles(files);
            });

            function handleFiles(files) {
                const newFiles = [...files];
                allFiles.push(...newFiles);
                updatePreview();
            }

            function updatePreview() {
                previewContainer.querySelectorAll('.new-preview').forEach(element => element.remove());
                allFiles.forEach(file => {
                    const reader = new FileReader();
                    reader.onload = (e) => {
                        const img = document.createElement('img');
                        img.src = e.target.result;
                        img.classList.add('preview-image', 'new-preview');
                        previewContainer.appendChild(img);
                    };
                    reader.readAsDataURL(file);
                });
            }

            form.addEventListener('submit', function(event) {
                event.preventDefault();

                const formData = new FormData(form);
                allFiles.forEach(file => {
                    formData.append('file', file);
                });

                fetch(form.action, {
                    method: form.method,
                    body: formData,
                }).then(response => {
                    if (response.ok) {
                        window.location.href = response.url;
                    } else {
                        console.error('Ha ocurrido un error al enviar el formulario.');
                    }
                }).catch(error => {
                    console.error('Ha ocurrido un error al enviar el formulario.', error);
                });
            });
        });
    </script>
</body>
</html>